name: univ_app
description: A new Flutter project.

publish_to: 'none'

version: 1.3.7+11

environment:
  sdk: '>=3.1.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  get:
  modal_progress_hud_nsn: ^0.5.0
  http: any
  shared_preferences: any
  dots_indicator: ^2.1.1
  flutter_search_bar: any
  carousel_slider: ^4.2.1
  email_validator: '^2.1.16'
  intl: ^0.18.1
  video_player: ^2.8.1
  image_picker: ^1.0.4
  geolocator: ^10.1.0
  flutter_otp_text_field: ^1.0.0
  youtube_player_flutter: ^8.1.2
  flutter_cache_manager: ^3.3.1
  cached_network_image: ^3.3.0
  sqflite: ^2.3.0
  internet_connection_checker: ^1.0.0+1
  permission_handler: ^11.2.0
  flare_flutter:
  visibility_detector: ^0.4.0+2
  story: ^1.1.0
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:
  fonts:
    - family: Billions
      fonts:
        - asset: assets/fonts/custom_font.ttf


  uses-material-design: true


  assets:
    - assets/